export enum EventTopic {
  CHAT = 'chat-events',
  POST = 'post-events',
  SHARE = 'share-events',
  INTERACTION = 'interaction',
  STATS = 'stats-events',
  GROUP = 'group-events',
  GROUP_CRUD = 'group-crud-events',
  USER = 'user-events',
  ANALYSIS = 'analysis-events',
  EMOTION_RESULT = 'emotion-result-events',
  MODERATION_REJECTED = 'moderation-rejected-events',
  LOGGING = 'logging-events',
  MEDIA = 'media-events',
  TEST_FAULT = 'test-fault',
}
