services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - '9092:9092' # external cho app dev (host)
      - '9093:9093' # internal cho kafka-ui
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
    mem_limit: 384m
    networks:
      - app-network
    volumes:
      - kafka_data:/var/lib/kafka/data

  # Vào production có thể bỏ qua kafka-ui
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
  #   depends_on:
  #     - kafka
  #   networks:
  #     - app-network

  redis:
    image: redis:7
    container_name: redis-micro
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-micro
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - '9200:9200'
    mem_limit: 512m
    networks:
      - app-network
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.1.7
  #   container_name: kibana
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - '5601:5601'
  #   networks:
  #     - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    mem_limit: 150m
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=6h'
      - '--storage.tsdb.retention.size=500MB'
    ports:
      - '9090:9090'
    mem_limit: 150m
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/etc/grafana/dashboards
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    mem_limit: 150m
    networks:
      - app-network

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - '4000:4000'
      - '5000:5000'
    env_file:
      - .env.production.local
      - apps/api-gateway/.env.production.local
    environment:
      - METRICS_PORT=5000
      - GATEWAY_PORT=4000
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BROKERS=kafka:9093
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - AI_CHATBOT_SERVICE_URL=http://ai-chatbot-service:4006
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  user-social-service:
    build:
      context: .
      dockerfile: apps/user-social-service/Dockerfile
    container_name: user-social-service
    restart: unless-stopped
    ports:
      - '4001:4001'
      - '5001:5001'
    env_file:
      - .env.production.local
      - apps/user-social-service/.env.production.local
    environment:
      - METRICS_PORT=5001
      - PORT=4001
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BROKERS=kafka:9093
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - rabbitmq
    networks:
      - app-network

  content-feed-service:
    build:
      context: .
      dockerfile: apps/content-feed-service/Dockerfile
    container_name: content-feed-service
    restart: unless-stopped
    ports:
      - '4002:4002'
      - '5002:5002'
    env_file:
      - .env.production.local
      - apps/content-feed-service/.env.production.local
    environment:
      - METRICS_PORT=5002
      - PORT=4002
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BROKERS=kafka:9093
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - rabbitmq
    networks:
      - app-network

  search-recommendation-service:
    build:
      context: .
      dockerfile: apps/search-recommendation-service/Dockerfile
    container_name: search-recommendation-service
    restart: unless-stopped
    ports:
      - '4003:4003'
      - '5003:5003'
    env_file:
      - .env.production.local
      - apps/search-recommendation-service/.env.production.local
    environment:
      - METRICS_PORT=5003
      - PORT=4003
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9093
      - ES_NODE=http://elasticsearch:9200
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - elasticsearch
    networks:
      - app-network

  chat-service:
    build:
      context: .
      dockerfile: apps/chat-service/Dockerfile
    container_name: chat-service
    restart: unless-stopped
    ports:
      - '4004:4004'
      - '5004:5004'
    env_file:
      - .env.production.local
      - apps/chat-service/.env.production.local
    environment:
      - METRICS_PORT=5004
      - PORT=4004
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BROKERS=kafka:9093
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - rabbitmq
    networks:
      - app-network

  emotion-intelligence-service:
    build:
      context: .
      dockerfile: apps/emotion-intelligence-service/Dockerfile
    container_name: emotion-intelligence-service
    restart: unless-stopped
    ports:
      - '4005:4005'
      - '5005:5005'
    env_file:
      - .env.production.local
      - apps/emotion-intelligence-service/.env.production.local
    environment:
      - METRICS_PORT=5005
      - PORT=4005
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_BROKERS=kafka:9093
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - rabbitmq
    networks:
      - app-network

  ai-chatbot-service:
    build:
      context: ./apps/ai-chatbot-service
      dockerfile: Dockerfile
    container_name: ai-chatbot-service
    restart: unless-stopped
    ports:
      - '4006:4006'
      - '5006:5006'
    env_file:
      - .env.production.local
      - apps/ai-chatbot-service/.env.production.local
    environment:
      - METRICS_PORT=5006
      - PORT=4006
      - REDIS_HOST=redis
      - CHATBOT_REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:9093
      - ES_NODE=http://elasticsearch:9200
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - USER_SOCIAL_SERVICE_HOST=user-social-service
      - CONTENT_FEED_SERVICE_HOST=content-feed-service
      - CHAT_SERVICE_HOST=chat-service
      - EMOTION_INTELLIGENCE_SERVICE_HOST=emotion-intelligence-service
      - SEARCH_RECOMMENDATION_SERVICE_HOST=search-recommendation-service
    depends_on:
      - redis
      - kafka
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  kafka_data:
  redis_data:
  rabbitmq_data:
  elastic_data:
