export enum GroupPermission {
  MANAGE_GROUP = 'MANAGE_GROUP',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  APPROVE_POST = 'APPROVE_POST',
  DELETE_POST = 'DELETE_POST',
  PIN_POST = 'PIN_POST',
  BAN_MEMBER = 'BAN_MEMBER',
  VIEW_REPORTS = 'VIEW_REPORTS',
  UPDATE_GROUP = 'UPDATE_GROUP',
  UPDATE_GROUP_SETTINGS = 'UPDATE_GROUP_SETTINGS',
  MANAGE_EVENTS = 'MANAGE_EVENTS',
  DELETE_GROUP = 'DELETE_GROUP',
}
