export enum GroupEventLog {
  // GROUP
  GROUP_UPDATED = 'GROUP_UPDATED',

  // SETTING
  GROUP_SETTING_CHANGED = 'GROUP_SETTING_CHANGED',

  // MEMBER
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBER_BANNED = 'MEMBER_BANNED',
  MEMBER_UNBANNED = 'MEMBER_UNBANNED',

  // ROLE & PERMISSION
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_PERMISSION_CHANGED = 'MEMBER_PERMISSION_CHANGED',
}
