﻿from __future__ import annotations

from dataclasses import dataclass


TEENCODE_MAP = {
    "ko": "khong",
    "k": "khong",
    "dc": "duoc",
    "đc": "duoc",
    "ntn": "nhu the nao",
    "ib": "inbox",
    "rep": "reply",
    "ad": "admin",
    "mn": "moi nguoi",
    "mik": "minh",
    "tui": "toi",
}


@dataclass(frozen=True)
class DomainKeywordGroup:
    domain: str
    keywords: set[str]


DOMAIN_KEYWORD_GROUPS: tuple[DomainKeywordGroup, ...] = (
    DomainKeywordGroup(
        "system",
        {
            "sentimeta",
            "se121",
            "he thong",
            "ung dung",
            "tinh nang",
            "mang xa hoi",
            "assistant",
            "chatbot",
        },
    ),
    DomainKeywordGroup(
        "chat",
        {
            "chat",
            "tin nhan",
            "nhan tin",
            "inbox",
            "conversation",
            "message",
            "messages",
            "dm",
        },
    ),
    DomainKeywordGroup(
        "post",
        {
            "bai viet",
            "bai dang",
            "dang bai",
            "feed",
            "newfeed",
            "post",
            "posts",
            "caption",
        },
    ),
    DomainKeywordGroup(
        "group",
        {
            "group",
            "nhom",
            "cong dong",
            "tham gia nhom",
            "nhom kin",
        },
    ),
    DomainKeywordGroup(
        "search",
        {
            "search",
            "tim",
            "tim kiem",
            "tra cuu",
            "lookup",
            "find",
            "find posts",
        },
    ),
    DomainKeywordGroup(
        "user_social",
        {
            "user",
            "tai khoan",
            "profile",
            "ho so",
            "ban be",
            "ket ban",
            "goi y ban be",
            "recommendation",
            "friend",
        },
    ),
    DomainKeywordGroup(
        "privacy",
        {
            "quyen rieng tu",
            "chinh sach rieng tu",
            "chinh sach bao mat",
            "bao mat",
            "du lieu ca nhan",
            "thong tin ca nhan",
            "block",
            "chan nguoi dung",
            "privacy",
            "privacy policy",
            "privacy settings",
            "data policy",
            "personal data",
        },
    ),
    DomainKeywordGroup(
        "notification",
        {
            "thong bao",
            "notification",
            "notifications",
        },
    ),
    DomainKeywordGroup(
        "emotion",
        {
            "cam xuc",
            "phan tich cam xuc",
            "sentiment",
            "emotion",
        },
    ),
    DomainKeywordGroup(
        "memory",
        {
            "ban con nho",
            "nho noi dung truoc do",
            "tom tat cuoc tro chuyen",
            "conversation history",
            "chat history",
            "nho gi khong",
        },
    ),
)


FOLLOW_UP_REFERENCE_KEYWORDS = {
    "chuc nang tren",
    "tinh nang tren",
    "cai tren",
    "cai do",
    "cai nay",
    "no",
    "no do",
    "nhu tren",
    "nhu vay",
    "phia tren",
    "cai kia",
    "phan tren",
    "phan do",
    "phan nay",
    "muc tren",
    "muc do",
    "muc nay",
    "chuc nang do",
    "tinh nang do",
    "chuc nang nay",
    "tinh nang nay",
    "phim do",
    "nut do",
    "cho do",
    "do thi sao",
    "do la sao",
    "y tren",
    "y do",
    "van de do",
    "truong hop do",
    "cau do",
    "tiep theo",
    "sau do",
    "ke tiep",
    "roi sao nua",
    "sao nua",
    "sau nua",
    "tiep nua",
    "huong dan tiep",
    "cach dung",
    "cach su dung",
    "su dung nhu nao",
    "dung nhu nao",
    "lam nhu nao voi no",
    "lam sao de dung",
    "chi tiet hon",
    "giai thich them",
    "noi ro hon",
    "cu the hon",
    "cho vi du",
    "vi du cu the",
    "tom tat lai",
    "how to use",
    "how does it work",
    "can you explain more",
    "explain more",
    "more details",
    "in detail",
    "step by step",
    "what next",
    "then what",
    "how about that",
    "about that",
    "that one",
    "this one",
    "that part",
    "this part",
    "that section",
    "this section",
    "what next",
    "then what",
    "explain more",
    "giai thich them ve no",
    "cho vi du cu the",
    "buoc tiep theo",
    "cach dung cai do",
    "truoc do",
    "cai truoc do",
    "y truoc do",
    "van de truoc do",
}

STRONG_REFERENCE_KEYWORDS = {
    "chuc nang tren",
    "phan do",
    "muc nay",
    "that section",
    "this section",
    "that feature",
    "this feature",
}

GREETINGS = {
    "hi",
    "hello",
    "hey",
    "xin chao",
    "chao",
}

FEATURE_QUERY_KEYWORDS = {
    "co chuc nang",
    "co ho tro",
    "ho tro khong",
    "co khong",
    "duoc khong",
    "hien tai",
    "tinh nang",
    "feature",
    "support",
    "available",
    "co the",
    "co cho phep",
}
