export enum Severity {
  NONE = 'NONE',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum ModerationAction {
  ALLOW = 'ALLOW',
  ALLOW_WITH_WARNING = 'ALLOW_WITH_WARNING',
  ALLOW_WITH_SUPPORT = 'ALLOW_WITH_SUPPORT',
  HARD_BLOCK = 'HARD_BLOCK',
}

export enum ModerationLabel {
  CLEAN = 'CLEAN',
  PROFANITY_VENTING = 'PROFANITY_VENTING',
  HATE_SPEECH = 'HATE_SPEECH',
  EMOTIONAL_CRISIS = 'EMOTIONAL_CRISIS',
  ILLEGAL_PORN = 'ILLEGAL_PORN',
}
