export const MICROSERVICES_CLIENTS = {
  CONTENT_FEED_SERVICE: "CONTENT_FEED_SERVICE",
  USER_SOCIAL_SERVICE: "USER_SOCIAL_SERVICE",
  ANALYSIS_SERVICE: "ANALYSIS_SERVICE",
  CHAT_SERVICE: "CHAT_SERVICE",
  SEARCH_SERVICE: "SEARCH_SERVICE",
  EMOTION_INTELLIGENCE_SERVICE: "EMOTION_INTELLIGENCE_SERVICE",
  MUSIC_SERVICE: "MUSIC_SERVICE",
  SEARCH_RECOMMENDATION_SERVICE: "SEARCH_RECOMMENDATION_SERVICE",
};
