export const MICROSERVICES_CLIENTS = {
  USER_SERVICE: 'USER_SERVICE',
  POST_SERVICE: 'POST_SERVICE',
  ANALYSIS_SERVICE: 'ANALYSIS_SERVICE',
  MEDIA_SERVICE: 'MEDIA_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  SOCIAL_SERVICE: 'SOCIAL_SERVICE',
  FEED_SERVICE: 'FEED_SERVICE',
  GROUP_SERVICE: 'GROUP_SERVICE',
  SEARCH_SERVICE: 'SEARCH_SERVICE',
  LOG_SERVICE: 'LOG_SERVICE',
};
