export const MICROSERVICE_CLIENT = {
  SOCIAL_SERVICE: 'SOCIAL_SERVICE',
  GROUP_SERVICE: 'GROUP_SERVICE',
  ANALYSIS_SERVICE: 'ANALYSIS_SERVICE', // ⭐ NEW
};

export const SCORE_SCALE = 1e6;
export const TIME_SCALE = 1e13;
