"""Add HNSW index for profile_embeddings

Revision ID: 72f0fca5e8f7
Revises: 20260510_0010
Create Date: 2026-06-03 18:02:28.506289
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '72f0fca5e8f7'
down_revision = '20260510_0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profile_embeddings_embedding_vector_hnsw', table_name='profile_embeddings', postgresql_using='hnsw')
    op.create_index('idx_profile_embeddings_vector', 'profile_embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profile_embeddings_vector', table_name='profile_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_vector': 'vector_cosine_ops'})
    op.create_index('idx_profile_embeddings_embedding_vector_hnsw', 'profile_embeddings', ['embedding_vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
